services:
  api:
    build: ./api
    ports: ["3000:3000"]
    environment:
      - DATABASE_URL=file:/app/db/dev.db
      - NODE_ENV=development
    volumes:
      - ./db:/app/db
      - ./data:/app/data
    restart: unless-stopped

  web:
    build:
      context: ./web
      args:
        - VITE_API_URL=http://localhost:3001
    ports:
      - "5173:5173"
    depends_on:
      - api
    restart: unless-stopped
